name: Sync miniature-octo-barnacle Bucket
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload binary to S3 miniature-octo-barnacle bucket
    - uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl public-read --exclude '.git/*'
      env:
        FILE: ./app.js
        AWS_REGION: 'eu-central-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      run: echo Why the F Im so dumb